### ISSUE TITLE
SLD file required for new layers

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#120]
In dev mode, when I attempt to upload a layer without including an SLD in the list of files, I get the following error in my paster logs:

```
2012-01-04 15:40:42,412 ERROR [geonode.maps.views] Unexpected error during
upload.
Traceback (most recent call last):
  File "/home/dwins/Projects/opengeo/geonode/src/GeoNodePy/geonode/maps/views.py", line 904, in upload_layer
    return _uploader(request,saved_layer,form,base_file)
  File "/home/dwins/Projects/opengeo/geonode/src/GeoNodePy/geonode/maps/views.py", line 933, in _uploader
    request.session['import_sld_file'] = file.name
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by ischneider** [comment]
Found this yesterday, too - closed w/ https://github.com/opengeo/geonode/commit/208b8f955f46c4fae557536165aaa4eef1f2fb84
