### ISSUE TITLE
Perform Experiment to see if some geogig layers are causing CPU spikes

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1324]
some geoserver logs are showing complaints about mixed up srs's in a repo when rendering wks's

2016-01-29 19:11:41,041 ERROR [geotools.rendering] - The coordinate reference system must be the same for all objects.
org.opengis.geometry.MismatchedReferenceSystemException: The coordinate reference system must be the same for all objects.
    at org.geotools.geometry.jts.ReferencedEnvelope.ensureCompatibleReferenceSystem(ReferencedEnvelope.java:309)
    at org.geotools.geometry.jts.ReferencedEnvelope.expandToInclude(ReferencedEnvelope.java:561)
    at org.locationtech.geogig.geotools.data.GeogigFeatureReader.expandToInclude(GeogigFeatureReader.java:431)
    at org.locationtech.geogig.geotools.data.GeogigFeatureReader.getQueryBounds(GeogigFeatureReader.java:411)

**Comment by groldan** [comment]
wanna bet?

**Comment by zrouse-Boundless** [comment]
I bet a frosty beer

**Comment by groldan** [comment]
deal. I bet it does cause CPU spikes.

**Comment by zrouse-Boundless** [comment]
that was the side I was gonna bet

**Comment by Coop56** [comment]
No longer relevant, all of these components have been upgraded since.  Closing.
