### ISSUE TITLE
Add suport for raster files

### ISSUE THREAD

**Issue by ingenieroariel** [MapStory/mapstory-meta#142]
When uploading a raster file to Mapstory, the following error comes out:

```
Unexpected error during upload: Could not save the layer flood, there was an upload error: ('Server error', 500, 'No input stream for the provided source')
```

The same file uploads correctly to the latest master branch of GeoNode.

Here is a snippet of the log output from GeoNode:

```
[Tue Jan 24 12:53:26 2012] [error] >>> Step 4. Starting upload of [/tmp/tmpMN_1AK/Estimated risk index for flood hazard1.tif] to GeoServer...
[Tue Jan 24 12:53:26 2012] [error] Error during upload
[Tue Jan 24 12:53:26 2012] [error] Traceback (most recent call last):
[Tue Jan 24 12:53:26 2012] [error]   File "/var/lib/geonode/src/GeoNodePy/geonode/maps/upload.py", line 87, in save
[Tue Jan 24 12:53:26 2012] [error]     import_session = uploader.upload(base_file)
[Tue Jan 24 12:53:26 2012] [error]   File "/var/lib/geonode/src/gsuploader.py/src/gsuploader/uploader.py", line 52, in upload
[Tue Jan 24 12:53:26 2012] [error]     session.upload_task(files)
[Tue Jan 24 12:53:26 2012] [error]   File "/var/lib/geonode/src/gsuploader.py/src/gsuploader/api.py", line 252, in upload_task
[Tue Jan 24 12:53:26 2012] [error]     resp = self._client().post_multipart(url, files)
[Tue Jan 24 12:53:26 2012] [error]   File "/var/lib/geonode/src/gsuploader.py/src/gsuploader/uploader.py", line 165, in post_multipart
[Tue Jan 24 12:53:26 2012] [error]     'Content-Type' : 'multipart/form-data; boundary=%s' % BOUNDARY
[Tue Jan 24 12:53:26 2012] [error]   File "/var/lib/geonode/src/gsuploader.py/src/gsuploader/uploader.py", line 110, in _request
[Tue Jan 24 12:53:26 2012] [error]     raise Exception('Server error',content)
[Tue Jan 24 12:53:26 2012] [error] Exception: ('Server error', 'No input stream for the provided source')
```

**Comment by ingenieroariel** [comment]
Adding the file manually via GeoServer and then running updatelayers is a tested workaround.

**Comment by ischneider** [comment]
Closing as #669 covers this.
