### ISSUE TITLE
Profiles aren't showing content I own

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1551]
Looks like something regressed in the push to production and changes in explore?

![grab_profile_off](https://cloud.githubusercontent.com/assets/2573761/15016903/42f91d80-11e1-11e6-864c-f279d80373c5.jpg)

**Comment by travislbrundage** [comment]
Console gives this stack trace...

```
2https://s3.amazonaws.com/mapstory-static/static/importer/css/angular-wizard.min.css Failed to load resource: the server responded with a status of 403 (Forbidden)
angular.js:11358 Error: [$sce:insecurl] Blocked loading resource from url not allowed by $sceDelegate policy.  URL: https://s3.amazonaws.com/mapstory-static/static/osgeo_importer/partials/upload.html
http://errors.angularjs.org/1.3.0/$sce/insecurl?p0=https%3A%2F%2Fs3.amazonaws.com%2Fmapstory-static%2Fstatic%2Fosgeo_importer%2Fpartials%2Fupload.html
    at https://s3.amazonaws.com/mapstory-static/static/lib/js/angular.js:80:12
    at getTrusted (https://s3.amazonaws.com/mapstory-static/static/lib/js/angular.js:14952:17)
    at Object.sce.(anonymous function) [as getTrustedResourceUrl] (https://s3.amazonaws.com/mapstory-static/static/lib/js/angular.js:15637:16)
    at compileTemplateUrl (https://s3.amazonaws.com/mapstory-static/static/lib/js/angular.js:7781:29)
    at applyDirectivesToNode (https://s3.amazonaws.com/mapstory-static/static/lib/js/angular.js:7352:24)
    at compileNodes (https://s3.amazonaws.com/mapstory-static/static/lib/js/angular.js:6913:15)
    at compileNodes (https://s3.amazonaws.com/mapstory-static/static/lib/js/angular.js:6925:15)
    at compile (https://s3.amazonaws.com/mapstory-static/static/lib/js/angular.js:6834:15)
    at applyDirectivesToNode (https://s3.amazonaws.com/mapstory-static/static/lib/js/angular.js:7275:33)
    at compileNodes (https://s3.amazonaws.com/mapstory-static/static/lib/js/angular.js:6913:15)(anonymous function) @ angular.js:11358
4https://mapstory-static.s3.amazonaws.com/geonode/img/missing_thumb.png Failed to load resource: the server responded with a status of 403 (Forbidden)
https://s3.amazonaws.com/mapstory-static/static/importer/css/angular-wizard.min.css Failed to load resource: the server responded with a status of 403 (Forbidden)
```

Looks like I can wrap that line in our template on the profile_detail in something like `$sce.trustAsResourceUrl(src);` and it might work? Will give that a try.

**Comment by travislbrundage** [comment]
So the problem is I can't seem to embed angular template variables in the upload directive on the profile_detail page: https://github.com/MapStory/mapstory-geonode/blob/master/mapstory/templates/people/profile_detail.html#L289

So I'm not sure how to pass the link into `trustAsResourceUrl()`. I can bind to the directive in the javascript, but this results in some errors with the importer's template being loaded. Gives me this stack trace when clicking "Create StoryLayer":

```
angular.js:11358 Error: [$compile:tpload] Failed to load template: osgeo_importer/partials/uploadWizard.html
http://errors.angularjs.org/1.3.0/$compile/tpload?p0=osgeo_importer%2Fpartials%2FuploadWizard.html
    at angular.js:80
    at handleError (angular.js:15773)
    at processQueue (angular.js:12914)
    at angular.js:12930
    at Scope.$eval (angular.js:14123)
    at Scope.$digest (angular.js:13939)
    at Scope.$apply (angular.js:14227)
    at done (angular.js:9493)
    at completeRequest (angular.js:9678)
    at XMLHttpRequest.requestLoaded (angular.js:9621)
```

**Comment by jonpmarino** [comment]
this is magically fixed. closing for now.

**Comment by travislbrundage** [comment]
This was only hotfixed on production and requires a longterm solution.

For some reason it isn't accepting s3 links as whitelisted, and by default angular is claiming the link is insecure and blocking the whole page as a result.

The solutions I can think of are:
1. Figure out how to get the s3 link whitelisted correctly
2. Make our own custom branch of osgeo-importer and put the hotfix change on top of it (not ideal)
3. Hack the angular digest cycle to compile the template for this directive so that we can hack the URL to be trusted using `$sce.trustAsResourceUrl()` (not ideal, but probably less bad than 2)
4. Make a change to osgeo-importer which only uses `trustAsResourceUrl()` if the url is to the s3 link. (hackish, but possibly the best solution next to 1)
