### ISSUE TITLE
error verifying layer during upload

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#436]
this appears during the final stage of the upload.

```
StackTrace: Traceback (most recent call last):
File "/var/www/mapstory/wsgi/geonode/src/GeoNodePy/geonode/upload/views.py", line 494, in view
resp = _steps[step](req, upload_session)
File "/var/www/mapstory/wsgi/geonode/src/GeoNodePy/geonode/upload/views.py", line 388, in final_step_view
saved_layer = upload.final_step(upload_session, req.user)
File "/var/www/mapstory/wsgi/geonode/src/GeoNodePy/geonode/upload/upload.py", line 432, in final_step
raise Exception("Expected to find layer named '%s' in geoserver", name)
```

In many cases, the layer is present but is just not found - in other words, a subsequent view of the layer info page will work. Not sure what is causing this - caching on the gscatalog side or some type of race condition in geoserver.

**Comment by ischneider** [comment]
The problem appears when a failure occurs during the 'run' stage of the upload. When the user tries again, the uploader erroneously has moved on to the next step ('final') and the checks fail as the import never completed.

The correct behavior is to detect the error in the proxy progress view and reset the completed_step.

**Comment by ischneider** [comment]
hmm, addressed in opengeo/geonode@d61d3529cb3269113e668ff45001a73cdc143ca2

**Comment by ischneider** [comment]
Still some problems with this. Not clear how it's occurring but timing/caching cause should not be ruled out.

**Comment by ischneider** [comment]
Adding to appomattox - was easy to address again during upload work and I continue to get occasional errors related to this.

It will be hard to test if the fix prevents this, but it should at least cause no issues during uploads.
