### ISSUE TITLE
upload style error handling

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#491]
Need to handle missing elements better and notify the user.

Traceback (most recent call last):

  File "/var/www/mapstory/wsgi/geonode/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)

  File "/var/www/mapstory/wsgi/geonode/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, _args, *_kwargs)

  File "/var/www/mapstory/wsgi/mapstory/views.py", line 439, in upload_style
    name = data.get('name') or el[0].text

IndexError: list index out of range

**Comment by cholmes** [comment]
Can't test this as I'm not sure the problem. It's when uploading an sld? A bad sld? I guess I can just try a few different uploads.

**Comment by ischneider** [comment]
Specifically, the style name is computed from the first NamedLayer/name element found. If not found in the SLD, the name is required in the form. The fix makes it so a message is displayed when neither name is present.

I tested by just getting the existing SLD and removing the element.

**Comment by cholmes** [comment]
I never tested, but looks like we pushed to production, so I'm just going to close.
