### ISSUE TITLE
add ability to configure expires headers for gwc

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#498]
this is not covered by gsconfig at the moment

**Comment by ischneider** [comment]
Mostly complete but might have problems with layers with spaces.
Specifically, the NullPointerException and odd error message below:

Error configuring GWC for geonode:Khmer Polygons
Traceback (most recent call last):
  File "/home/geonode/mapstory/../mapstory/gwc_config.py", line 75, in configure_layer
    _configure_layer(typename)
  File "/home/geonode/mapstory/../mapstory/gwc_config.py", line 135, in _configure_layer
    % (headers.status, response))
Exception: expected success, got 500 - null java.lang.NullPointerException
Error configuring GWC for geonode:Khmer Polygons
Traceback (most recent call last):
  File "/home/geonode/mapstory/../mapstory/gwc_config.py", line 75, in configure_layer
    _configure_layer(typename)
  File "/home/geonode/mapstory/../mapstory/gwc_config.py", line 135, in _configure_layer
    % (headers.status, response))
Exception: expected success, got 500 - null java.lang.NullPointerException
Error configuring WMS caching for geonode:Khmer Polygons
Traceback (most recent call last):
  File "/home/geonode/mapstory/../mapstory/gwc_config.py", line 79, in configure_layer
    _enable_wms_caching(layer, cache_secs)
  File "/home/geonode/mapstory/../mapstory/gwc_config.py", line 66, in _enable_wms_caching
    raise Exception('error enabling wms caching: %s' % resp)
Exception: error enabling wms caching: No such feature type: geonode,geonode,Khmer
Error configuring WMS caching for geonode:Khmer Polygons
Traceback (most recent call last):
  File "/home/geonode/mapstory/../mapstory/gwc_config.py", line 79, in configure_layer
    _enable_wms_caching(layer, cache_secs)
  File "/home/geonode/mapstory/../mapstory/gwc_config.py", line 66, in _enable_wms_caching
    raise Exception('error enabling wms caching: %s' % resp)
Exception: error enabling wms caching: No such feature type: geonode,geonode,Khmer
