### ISSUE TITLE
caching proxy might be causing problems for some operations

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#712]
The reported error (via email) is:

> Traceback (most recent call last):
> 
>  File "/var/www/mapstory/wsgi/geonode/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
>    response = callback(request, _callback_args, *_callback_kwargs)
> 
>  File "/home/geonode/geonode/src/GeoNodePy/geonode/proxy/views.py", line 61, in geoserver_rest_proxy
>    body=request.raw_post_data or None,
> 
>  File "/var/www/mapstory/wsgi/geonode/lib/python2.6/site-packages/django/http/**init**.py", line 337, in raw_post_data
>    return self.body
> 
>  File "/var/www/mapstory/wsgi/geonode/lib/python2.6/site-packages/django/http/**init**.py", line 328, in body
>    self._body = self.read()
> 
>  File "/var/www/mapstory/wsgi/geonode/lib/python2.6/site-packages/django/http/**init**.py", line 384, in read
>    return self._stream.read(_args, *_kwargs)
> 
>  File "/var/www/mapstory/wsgi/geonode/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 98, in read
>    result = self.buffer + self._read_limited()
> 
>  File "/var/www/mapstory/wsgi/geonode/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 92, in _read_limited
>    result = self.stream.read(size)
> 
> UnreadablePostError: request data read error

This error basically means the client disconnected prematurely. This occurred (repeatedly) when a user attempted to upload an SLD.

The headers for this request included:
 'HTTP_CACHE_CONTROL': 'max-age=259200',
 'HTTP_REFERER': 'http://mapstory.org/maps/708/view/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.94 Safari/537.36',
 'HTTP_VIA': '1.1 NAMEREDACTED (squid/3.1.14)',

**Comment by ischneider** [comment]
Closing - maybe this will go away magically with django updates
